ALTER TABLE squad_members ALTER COLUMN joined_at TYPE TIMESTAMPTZ;

ALTER TABLE invites ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE invites ALTER COLUMN expires_at TYPE TIMESTAMPTZ;

ALTER TABLE squads ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN last_login TYPE TIMESTAMPTZ;